"""Grasshopper Mirror — README Generator

Paste this into a GhPython Script node on the Grasshopper canvas.

    Node setup
    ----------
    Inputs (all string, from panels):
        headline, tiny_description, tags, authors,
        headline_image_url, summary, origin_story,
        detailed_description, repo_url
    Output: out — status message

Target: Rhino 8+ / CPython 3.9

Generates a README.md with YAML frontmatter in the same directory
as the .gh file.
"""

import os


def get_filename():
    ghdoc = ghenv.Component.OnPingDocument()
    return os.path.basename(ghdoc.FilePath) if ghdoc.FilePath else "unknown.gh"


def get_directory():
    ghdoc = ghenv.Component.OnPingDocument()
    if not ghdoc.FilePath:
        return None
    return os.path.dirname(ghdoc.FilePath)


def build_tag_string(tags_input):
    lines = []
    for t in tags_input:
        lines.append(f"    - {t.strip()}")
    return "\n".join(lines)


def build_author_string(authors_input):
    lines = []
    for a in authors_input:
        parts = a.split("@")
        name = parts[0].strip()
        lines.append(f"    - name: {name}")
        if len(parts) > 1:
            gh_handle = parts[1].strip()
            lines.append(f"      github: {gh_handle}")
    return "\n".join(lines)


def generate_readme():
    directory = get_directory()
    if directory is None:
        return "Cannot save: document has no file path (save the .gh first)"

    filename = get_filename()
    tag_yaml = build_tag_string(tags)
    author_yaml = build_author_string(authors)

    doc = f"""---
tiny_description: {tiny_description}
repo_url: {repo_url}
tags:
{tag_yaml}
authors:
{author_yaml}
headline_image: {headline_image_url} # fully qualified domain name, not relative.

# NOTE: this file is autogenerated from the GH component
---

# {headline} ({filename})

![An image of what this file actually does](headline_image.PNG)
![A screenshot of the grasshopper canvas](canvas_image.png)

## Summary:

_A **very** short explanation of what this does._

{summary}

## Origin story:

_Why did this file come into being?_

{origin_story}

## Detailed description:

_A much longer explanation of what this does._

{detailed_description}

"""

    path = os.path.join(directory, "README.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(doc)

    return f"Saved README to {path}"


a = generate_readme()
