"""Grasshopper Mirror — README Generator

Generates a README.md with YAML frontmatter next to the .gh file.

Public API
----------
    generate_readme(gh_doc, headline, tiny_description, tags, authors,
                    headline_image_url, summary, origin_story,
                    detailed_description, repo_url) → str
"""

import os

from mirror_common import doc_dir, write_text


def _get_filename(gh_doc):
    fp = gh_doc.FilePath
    return os.path.basename(fp) if fp else "unknown.gh"


def _build_tag_string(tags_input):
    lines = []
    for t in tags_input:
        lines.append(f"    - {t.strip()}")
    return "\n".join(lines)


def _build_author_string(authors_input):
    lines = []
    for a in authors_input:
        parts = a.split("@")
        name = parts[0].strip()
        lines.append(f"    - name: {name}")
        if len(parts) > 1:
            gh_handle = parts[1].strip()
            lines.append(f"      github: {gh_handle}")
    return "\n".join(lines)


def generate_readme(gh_doc, headline, tiny_description, tags, authors,
                    headline_image_url, summary, origin_story,
                    detailed_description, repo_url):
    """Generate README.md and write to disk next to the .gh file."""
    directory = doc_dir(gh_doc)
    if directory is None:
        return "Cannot save: document has no file path (save the .gh first)"

    filename = _get_filename(gh_doc)
    tag_yaml = _build_tag_string(tags)
    author_yaml = _build_author_string(authors)

    doc = f"""---
tiny_description: {tiny_description}
repo_url: {repo_url}
tags:
{tag_yaml}
authors:
{author_yaml}
headline_image: {headline_image_url} # fully qualified domain name, not relative.

# NOTE: this file is autogenerated from the GH component
---

# {headline} ({filename})

![An image of what this file actually does](headline_image.PNG)
![A screenshot of the grasshopper canvas](canvas_image.png)

## Summary:

_A **very** short explanation of what this does._

{summary}

## Origin story:

_Why did this file come into being?_

{origin_story}

## Detailed description:

_A much longer explanation of what this does._

{detailed_description}

"""

    path = os.path.join(directory, "README.md")
    write_text(path, doc)
    return f"Saved README to {path}"
